# Generated by Django 4.2.23 on 2025-08-08 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DVLAA', '0003_remove_booking_booking_date_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvlaa_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
