# Generated by Django 5.2.1 on 2025-07-28 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAYPAL', '0003_remove_booking_scheduled_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment_completed',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mot_class',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_mileage',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_registration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
