# Generated by Django 5.2.1 on 2025-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAYPAL', '0004_rename_payment_completed_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
