# Generated by Django 5.2.1 on 2025-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAYPAL', '0006_booking_card_number_booking_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='booking',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cvv',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='mot_class',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='card', max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_mileage',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
