# Generated by Django 4.2.23 on 2025-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAYPAL', '0007_rename_created_at_booking_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
